### PR TITLE
do not compile on change

### LINKED ISSUE #144: didChange shouldn't recompile
We respond to `textDocument/didChange` with a [recompile](https://github.com/palantir/language-servers/blob/develop/language-server-commons/src/main/java/com/palantir/ls/services/AbstractTextDocumentService.java#L86).

We should only compile on `textDocument/didSave`.

### PR DESCRIPTION
**Pull request by ags799**
Closes #144

### CODE REVIEW

**Comment by darora** [comment]
lgtm

**Comment by jiahuijiang** [comment]
@darora @ags799 right now bascially nothing inside groovy language server works unless the content on the frontend is exactly the same as the version just saved.
Other language servers also parse on didChange
https://github.com/Microsoft/vscode/blob/master/extensions/json/server/src/jsonServerMain.ts#L199
I still think it should be handled on the frontend

**Comment by ags799** [comment]
maybe we should compile on every change but not publish diagnostics? would that help?

**Comment by jiahuijiang** [comment]
publishDianostics is very light weight, it's simply getting the errors from the compiled results and send it back to the frontend. I because on the frontend the work needed is also very tiny

**Pull request merged**
